/**
 * Jiskefet
 * Running with /api base path
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.4.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SettingApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_SettingApi_H_
#define IO_SWAGGER_CLIENT_API_SettingApi_H_


#include "../ApiClient.h"


#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  SettingApi
{
public:
    SettingApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~SettingApi();
    /// <summary>
    /// Returns settings.
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<void> settingGet(
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_SettingApi_H_ */

