/**
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * CreateLogDto.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_CreateLogDto_H_
#define IO_SWAGGER_CLIENT_MODEL_CreateLogDto_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  CreateLogDto
    : public ModelBase
{
public:
    CreateLogDto();
    virtual ~CreateLogDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateLogDto members

    /// <summary>
    /// What kind of log is it?
    /// </summary>
    utility::string_t getSubtype() const;
        void setSubtype(utility::string_t value);
    /// <summary>
    /// Where did the log come from?
    /// </summary>
    utility::string_t getOrigin() const;
        void setOrigin(utility::string_t value);
    /// <summary>
    /// describes the log in short
    /// </summary>
    utility::string_t getTitle() const;
        void setTitle(utility::string_t value);
    /// <summary>
    /// describes the log in depth
    /// </summary>
    utility::string_t getText() const;
        void setText(utility::string_t value);
    /// <summary>
    /// Attachments of this log
    /// </summary>
    std::vector<utility::string_t>& getAttachments();
        void setAttachments(std::vector<utility::string_t> value);
    /// <summary>
    /// Attached run numbers of this log
    /// </summary>
    std::vector<utility::string_t>& getRuns();
        void setRuns(std::vector<utility::string_t> value);

protected:
    utility::string_t m_Subtype;
        utility::string_t m_Origin;
        utility::string_t m_Title;
        utility::string_t m_Text;
        std::vector<utility::string_t> m_Attachments;
        std::vector<utility::string_t> m_Runs;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_CreateLogDto_H_ */
