/**
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * CreateRunDto.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_CreateRunDto_H_
#define IO_SWAGGER_CLIENT_MODEL_CreateRunDto_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  CreateRunDto
    : public ModelBase
{
public:
    CreateRunDto();
    virtual ~CreateRunDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateRunDto members

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getTimeO2Start() const;
        void setTimeO2Start(utility::datetime value);
    /// <summary>
    /// 
    /// </summary>
    utility::datetime getTimeTrgStart() const;
        void setTimeTrgStart(utility::datetime value);
    /// <summary>
    /// 
    /// </summary>
    utility::datetime getTimeO2End() const;
        void setTimeO2End(utility::datetime value);
    /// <summary>
    /// 
    /// </summary>
    utility::datetime getTimeTrgEnd() const;
        void setTimeTrgEnd(utility::datetime value);
    /// <summary>
    /// What kind of run.
    /// </summary>
    utility::string_t getRunType() const;
        void setRunType(utility::string_t value);
    /// <summary>
    /// The quality of the run.
    /// </summary>
    utility::string_t getRunQuality() const;
        void setRunQuality(utility::string_t value);
    /// <summary>
    /// The id of the activity.
    /// </summary>
    utility::string_t getActivityId() const;
        void setActivityId(utility::string_t value);
    /// <summary>
    /// Number of detectors during run.
    /// </summary>
    int32_t getNDetectors() const;
        void setNDetectors(int32_t value);
    /// <summary>
    /// Number of FLPs that computed data
    /// </summary>
    int32_t getNFlps() const;
        void setNFlps(int32_t value);
    /// <summary>
    /// Number of EPNs that stored data
    /// </summary>
    int32_t getNEpns() const;
        void setNEpns(int32_t value);
    /// <summary>
    /// Number of timeframes
    /// </summary>
    int32_t getNTimeframes() const;
        void setNTimeframes(int32_t value);
    /// <summary>
    /// Number of subtimeframes
    /// </summary>
    int32_t getNSubtimeframes() const;
        void setNSubtimeframes(int32_t value);
    /// <summary>
    /// Amount of bytes read out
    /// </summary>
    int32_t getBytesReadOut() const;
        void setBytesReadOut(int32_t value);
    /// <summary>
    /// What builder was used.
    /// </summary>
    int32_t getBytesTimeframeBuilder() const;
        void setBytesTimeframeBuilder(int32_t value);

protected:
    utility::datetime m_TimeO2Start;
        utility::datetime m_TimeTrgStart;
        utility::datetime m_TimeO2End;
        utility::datetime m_TimeTrgEnd;
        utility::string_t m_RunType;
        utility::string_t m_RunQuality;
        utility::string_t m_ActivityId;
        int32_t m_NDetectors;
        int32_t m_NFlps;
        int32_t m_NEpns;
        int32_t m_NTimeframes;
        int32_t m_NSubtimeframes;
        int32_t m_BytesReadOut;
        int32_t m_BytesTimeframeBuilder;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_CreateRunDto_H_ */
