/**
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "LinkLogToRunDto.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

LinkLogToRunDto::LinkLogToRunDto()
{
    m_LogId = 0;
}

LinkLogToRunDto::~LinkLogToRunDto()
{
}

void LinkLogToRunDto::validate()
{
    // TODO: implement validation
}

web::json::value LinkLogToRunDto::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("logId")] = ModelBase::toJson(m_LogId);

    return val;
}

void LinkLogToRunDto::fromJson(web::json::value& val)
{
    setLogId(ModelBase::int32_tFromJson(val[utility::conversions::to_string_t("logId")]));
}

void LinkLogToRunDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("logId"), m_LogId));
}

void LinkLogToRunDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setLogId(ModelBase::int32_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("logId"))));
}

int32_t LinkLogToRunDto::getLogId() const
{
    return m_LogId;
}


void LinkLogToRunDto::setLogId(int32_t value)
{
    m_LogId = value;
    
}
}
}
}
}

