/**
 * Jiskefet
 * Running with /api base path
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.2.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * PatchRunDto.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_PatchRunDto_H_
#define IO_SWAGGER_CLIENT_MODEL_PatchRunDto_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  PatchRunDto
    : public ModelBase
{
public:
    PatchRunDto();
    virtual ~PatchRunDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PatchRunDto members

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getTrgEndTime() const;
        void setTrgEndTime(utility::datetime value);
    /// <summary>
    /// 
    /// </summary>
    utility::datetime getO2EndTime() const;
        void setO2EndTime(utility::datetime value);
    /// <summary>
    /// The quality of the run.
    /// </summary>
    utility::string_t getRunQuality() const;
        void setRunQuality(utility::string_t value);
    /// <summary>
    /// Number of timeframes
    /// </summary>
    double getNTimeframes() const;
        void setNTimeframes(double value);
    /// <summary>
    /// Number of subtimeframes
    /// </summary>
    double getNSubtimeframes() const;
        void setNSubtimeframes(double value);
    /// <summary>
    /// Amount of bytes read out
    /// </summary>
    double getBytesReadOut() const;
        void setBytesReadOut(double value);
    /// <summary>
    /// What builder was used.
    /// </summary>
    double getBytesTimeframeBuilder() const;
        void setBytesTimeframeBuilder(double value);

protected:
    utility::datetime m_TrgEndTime;
        utility::datetime m_O2EndTime;
        utility::string_t m_RunQuality;
        double m_NTimeframes;
        double m_NSubtimeframes;
        double m_BytesReadOut;
        double m_BytesTimeframeBuilder;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_PatchRunDto_H_ */
