/**
 * Jiskefet
 * Running with /api base path
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.4.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * CreateRunDto.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_CreateRunDto_H_
#define IO_SWAGGER_CLIENT_MODEL_CreateRunDto_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  CreateRunDto
    : public ModelBase
{
public:
    CreateRunDto();
    virtual ~CreateRunDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateRunDto members

    /// <summary>
    /// The id of the run
    /// </summary>
    int64_t getRunNumber() const;
        void setRunNumber(int64_t value);
    /// <summary>
    /// Current Date
    /// </summary>
    utility::datetime getO2StartTime() const;
        void setO2StartTime(utility::datetime value);
    /// <summary>
    /// Current Date
    /// </summary>
    utility::datetime getTrgStartTime() const;
        void setTrgStartTime(utility::datetime value);
    /// <summary>
    /// What kind of run.
    /// </summary>
    utility::string_t getRunType() const;
        void setRunType(utility::string_t value);
    /// <summary>
    /// The id of the activity.
    /// </summary>
    utility::string_t getActivityId() const;
        void setActivityId(utility::string_t value);
    /// <summary>
    /// Number of detectors during run.
    /// </summary>
    int64_t getNDetectors() const;
        void setNDetectors(int64_t value);
    /// <summary>
    /// Number of FLPs that computed data
    /// </summary>
    int64_t getNFlps() const;
        void setNFlps(int64_t value);
    /// <summary>
    /// Number of EPNs that stored data
    /// </summary>
    int64_t getNEpns() const;
        void setNEpns(int64_t value);

protected:
    int64_t m_RunNumber;
        utility::datetime m_O2StartTime;
        utility::datetime m_TrgStartTime;
        utility::string_t m_RunType;
        utility::string_t m_ActivityId;
        int64_t m_NDetectors;
        int64_t m_NFlps;
        int64_t m_NEpns;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_CreateRunDto_H_ */
