/**
 * Jiskefet
 * Running with /api base path
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.4.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * CreateFlpDto.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_CreateFlpDto_H_
#define IO_SWAGGER_CLIENT_MODEL_CreateFlpDto_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  CreateFlpDto
    : public ModelBase
{
public:
    CreateFlpDto();
    virtual ~CreateFlpDto();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateFlpDto members

    /// <summary>
    /// Name of the flp
    /// </summary>
    utility::string_t getFlpName() const;
        void setFlpName(utility::string_t value);
    /// <summary>
    /// Name of the hostmachine, where the flp comes from.
    /// </summary>
    utility::string_t getFlpHostname() const;
        void setFlpHostname(utility::string_t value);
    /// <summary>
    /// Attached run numbers of this log
    /// </summary>
    int64_t getRun() const;
        void setRun(int64_t value);

protected:
    utility::string_t m_FlpName;
        utility::string_t m_FlpHostname;
        int64_t m_Run;
    };

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_CreateFlpDto_H_ */
