/**
 * Jiskefet
 * Running with /api base path
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.4.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "FlpRole.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

FlpRole::FlpRole()
{
}

FlpRole::~FlpRole()
{
}

void FlpRole::validate()
{
    // TODO: implement validation
}

web::json::value FlpRole::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("run")] = ModelBase::toJson(m_Run);

    return val;
}

void FlpRole::fromJson(web::json::value& val)
{
    std::shared_ptr<Object> newRun(nullptr);
    newRun->fromJson(val[utility::conversions::to_string_t("run")]);
    setRun( newRun );
}

void FlpRole::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    m_Run->toMultipart(multipart, utility::conversions::to_string_t("run."));
}

void FlpRole::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    std::shared_ptr<Object> newRun(nullptr);
    newRun->fromMultiPart(multipart, utility::conversions::to_string_t("run."));
    setRun( newRun );
}

std::shared_ptr<Object> FlpRole::getRun() const
{
    return m_Run;
}


void FlpRole::setRun(std::shared_ptr<Object> value)
{
    m_Run = value;
    
}
}
}
}
}

