/**
 * Jiskefet
 * Running with /api base path
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.4.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "LinkRunToLogDto.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

LinkRunToLogDto::LinkRunToLogDto()
{
    m_RunNumber = 0L;
}

LinkRunToLogDto::~LinkRunToLogDto()
{
}

void LinkRunToLogDto::validate()
{
    // TODO: implement validation
}

web::json::value LinkRunToLogDto::toJson() const
{
    web::json::value val = web::json::value::object();

    val[utility::conversions::to_string_t("runNumber")] = ModelBase::toJson(m_RunNumber);

    return val;
}

void LinkRunToLogDto::fromJson(web::json::value& val)
{
    setRunNumber(ModelBase::int64_tFromJson(val[utility::conversions::to_string_t("runNumber")]));
}

void LinkRunToLogDto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("runNumber"), m_RunNumber));
}

void LinkRunToLogDto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    setRunNumber(ModelBase::int64_tFromHttpContent(multipart->getContent(utility::conversions::to_string_t("runNumber"))));
}

int64_t LinkRunToLogDto::getRunNumber() const
{
    return m_RunNumber;
}


void LinkRunToLogDto::setRunNumber(int64_t value)
{
    m_RunNumber = value;
    
}
}
}
}
}

