/**
 * Jiskefet
 * Running with /api prefix
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.1-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * AttachmentsApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_AttachmentsApi_H_
#define IO_SWAGGER_CLIENT_API_AttachmentsApi_H_


#include "../ApiClient.h"

#include "CreateAttachmentDto.h"
#include "Object.h"

#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  AttachmentsApi
{
public:
    AttachmentsApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~AttachmentsApi();
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id"></param>
    pplx::task<std::shared_ptr<Object>> attachmentsIdLogsGet(
        int32_t id
    );
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="createAttachmentDto"></param>
    pplx::task<void> attachmentsPost(
        std::shared_ptr<CreateAttachmentDto> createAttachmentDto
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_AttachmentsApi_H_ */

